version: "3.7"
services:
    server:
        image: rsd-server
        build: ./server
        restart: always
        environment:
            - NODE_ENV=production
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - postgres
    postgres:
        image: mdillon/postgis
        restart: always
        container_name: postgres
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - 54322:5432